# Generated by Django 5.0.4 on 2024-04-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chatmessage_message_alter_chatmessage_receiver_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
