# Generated by Django 5.0.4 on 2024-04-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
