# Generated by Django 5.0.4 on 2024-04-14 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_profile_bio_alter_profile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_read',
        ),
    ]
